# Generated by Django 3.2.1 on 2021-05-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210506_1246'),
        ('File', '0002_alter_projectteam_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowApprovers',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='借阅记录和审批人映射编号')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'dms_borrow_approvers',
            },
        ),
        migrations.CreateModel(
            name='BorrowNotifyers',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='借阅记录和抄送人映射编号')),
            ],
            options={
                'db_table': 'dms_borrow_notifyers',
            },
        ),
        migrations.CreateModel(
            name='CabinetsManagers',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件柜管理员映射编号')),
            ],
            options={
                'db_table': 'dms_cabinets_managers',
            },
        ),
        migrations.CreateModel(
            name='CasesManagers',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件柜格管理员映射编号')),
            ],
            options={
                'db_table': 'dms_cases_managers',
            },
        ),
        migrations.CreateModel(
            name='CasesPermissions',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件柜格和开放权限用户映射编号')),
            ],
            options={
                'db_table': 'dms_cases_permissions',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件编号')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('_type', models.CharField(db_column='type', max_length=255, verbose_name='文件类型')),
                ('current_version_id', models.IntegerField(null=True, verbose_name='版本编号')),
                ('is_activated', models.BooleanField(default=True, verbose_name='是否存活')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='User.user')),
            ],
            options={
                'db_table': 'dms_files',
            },
        ),
        migrations.CreateModel(
            name='FilingCabinet',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件柜编号')),
                ('name', models.CharField(max_length=255, verbose_name='文件柜名称')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('managers', models.ManyToManyField(related_name='manage_cabinets', through='File.CabinetsManagers', to='User.User')),
            ],
            options={
                'db_table': 'dms_filing_cabinets',
            },
        ),
        migrations.AlterModelTable(
            name='projectteam',
            table='dms_project_teams',
        ),
        migrations.CreateModel(
            name='FilingCase',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件柜格编号')),
                ('name', models.CharField(max_length=255, verbose_name='文件柜格名称')),
                ('_type', models.CharField(db_column='type', max_length=255, verbose_name='柜格类型')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('managers', models.ManyToManyField(related_name='manage_cases', through='File.CasesManagers', to='User.User')),
                ('permission_users', models.ManyToManyField(related_name='permit_cases', through='File.CasesPermissions', to='User.User')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filingcases', to='File.filingcabinet')),
            ],
            options={
                'db_table': 'dms_filing_cases',
            },
        ),
        migrations.AddField(
            model_name='filingcabinet',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filingcabinets', to='File.projectteam'),
        ),
        migrations.CreateModel(
            name='FilingBox',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件盒编号')),
                ('name', models.CharField(max_length=255, verbose_name='文件柜名称')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filingboxes', to='File.filingcase')),
            ],
            options={
                'db_table': 'dms_filing_boxes',
            },
        ),
        migrations.CreateModel(
            name='FileVersions',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='版本编号')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='版本描述')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='存放路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存活')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='File.file')),
            ],
            options={
                'db_table': 'dms_file_versions',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='File.filingbox'),
        ),
        migrations.AddField(
            model_name='casespermissions',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.filingcase'),
        ),
        migrations.AddField(
            model_name='casespermissions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='casesmanagers',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.filingcase'),
        ),
        migrations.AddField(
            model_name='casesmanagers',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='cabinetsmanagers',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.filingcabinet'),
        ),
        migrations.AddField(
            model_name='cabinetsmanagers',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.CreateModel(
            name='BorrowRecords',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='借阅编号')),
                ('borrow_version_id', models.IntegerField(null=True, verbose_name='借阅时的版本编号')),
                ('reason', models.CharField(max_length=255, null=True, verbose_name='借阅事由')),
                ('bstime', models.DateTimeField(null=True, verbose_name='借阅起始时间')),
                ('betime', models.DateTimeField(null=True, verbose_name='借阅结束时间')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='借阅记录创建时间')),
                ('ptime', models.DateTimeField(null=True, verbose_name='通过审批时间')),
                ('etime', models.DateTimeField(null=True, verbose_name='归还时间')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('opinion', models.CharField(max_length=255, null=True, verbose_name='审批意见')),
                ('status', models.IntegerField(default=0, verbose_name='借阅记录状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存活')),
                ('approvers', models.ManyToManyField(related_name='approve_records', through='File.BorrowApprovers', to='User.User')),
                ('borrow_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowrecords', to='File.file')),
                ('borrow_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowrecords', to='User.user')),
                ('notifyers', models.ManyToManyField(related_name='notify_records', through='File.BorrowNotifyers', to='User.User')),
            ],
            options={
                'db_table': 'dms_borrow_records',
            },
        ),
        migrations.AddField(
            model_name='borrownotifyers',
            name='borrow_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.borrowrecords'),
        ),
        migrations.AddField(
            model_name='borrownotifyers',
            name='notifyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
        migrations.AddField(
            model_name='borrowapprovers',
            name='borrow_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.borrowrecords'),
        ),
    ]
