# Generated by Django 3.2.1 on 2021-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_auto_20210506_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='superior_type',
            field=models.BooleanField(default=0, verbose_name='上层位置类型'),
        ),
        migrations.AlterField(
            model_name='file',
            name='position',
            field=models.IntegerField(null=True, verbose_name='上层位置编号'),
        ),
    ]
