# Generated by Django 3.2.1 on 2021-05-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0004_auto_20210509_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingcase',
            name='remark',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
    ]
