# Generated by Django 3.2.1 on 2021-05-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0006_projectteam_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='is_activated',
            new_name='is_active',
        ),
    ]
