# Generated by Django 3.2.1 on 2021-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0007_rename_is_activated_file_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileversions',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='存放路径'),
        ),
    ]
