# Generated by Django 3.2.1 on 2021-05-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_borrow_count'),
        ('File', '0008_auto_20210515_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingbox',
            name='name',
            field=models.CharField(max_length=255, verbose_name='文件盒名称'),
        ),
        migrations.CreateModel(
            name='ProjectTeamManagers',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='项目组管理员映射编号')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('project_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.projectteam')),
            ],
            options={
                'db_table': 'dms_project_team_managers',
            },
        ),
        migrations.AddField(
            model_name='projectteam',
            name='managers',
            field=models.ManyToManyField(related_name='manage_project_team', through='File.ProjectTeamManagers', to='User.User'),
        ),
    ]
