# Generated by Django 3.2.1 on 2021-05-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0009_auto_20210521_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='项目组编号'),
        ),
    ]
