# Generated by Django 3.2.1 on 2021-05-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_borrow_count'),
        ('File', '0010_alter_projectteam__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecords',
            name='real_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approverecords', to='User.user'),
        ),
    ]
