# Generated by Django 3.2.1 on 2021-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0011_borrowrecords_real_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecords',
            name='show_user',
            field=models.BooleanField(default=1, verbose_name='是否展示给员工'),
        ),
    ]
