# Generated by Django 3.2.1 on 2021-05-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0012_borrowrecords_show_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecords',
            name='urge',
            field=models.BooleanField(default=0, verbose_name='是否催办'),
        ),
    ]
