# Generated by Django 3.2.1 on 2021-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0013_borrowrecords_urge'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingbox',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='是否存活'),
        ),
        migrations.AlterField(
            model_name='borrowrecords',
            name='ptime',
            field=models.DateTimeField(null=True, verbose_name='审批时间'),
        ),
    ]
