# Generated by Django 3.2.1 on 2021-05-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_borrow_count'),
        ('File', '0014_auto_20210526_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingAudit',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件柜台账编号')),
                ('level', models.IntegerField(default=1, verbose_name='文件柜结构的层次')),
                ('filing_id', models.IntegerField(default=1, verbose_name='文件柜结构的编号')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation', models.CharField(max_length=255, null=True, verbose_name='操作类型')),
                ('target', models.CharField(max_length=255, null=True, verbose_name='当时的操作对象')),
                ('name_vary', models.CharField(max_length=255, null=True, verbose_name='名称的变化')),
                ('permit_users_vary', models.CharField(max_length=255, null=True, verbose_name='开启权限用户的变化')),
                ('position_vary', models.CharField(max_length=255, null=True, verbose_name='位置的变化')),
                ('remark_vary', models.CharField(max_length=255, null=True, verbose_name='备注的变化')),
                ('operate_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'dms_filing_audit',
            },
        ),
        migrations.CreateModel(
            name='FileAudit',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='文件台账编号')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation', models.CharField(max_length=255, null=True, verbose_name='操作类型')),
                ('target', models.CharField(max_length=255, null=True, verbose_name='当时的操作对象')),
                ('name_vary', models.CharField(max_length=255, null=True, verbose_name='名称的变化')),
                ('version_vary', models.CharField(max_length=255, null=True, verbose_name='文件版本的变化')),
                ('position_vary', models.CharField(max_length=255, null=True, verbose_name='位置的变化')),
                ('remark_vary', models.CharField(max_length=255, null=True, verbose_name='备注的变化')),
                ('operate_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='File.file')),
                ('operate_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'dms_file_audit',
            },
        ),
    ]
