# Generated by Django 3.2.1 on 2021-05-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='dms_roles',
        ),
    ]
