# Generated by Django 3.2.1 on 2021-05-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_role_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('_id', models.IntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='权限编号')),
                ('description', models.CharField(max_length=255, verbose_name='权限描述')),
            ],
            options={
                'db_table': 'dms_permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False, verbose_name='工号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('wechat', models.CharField(max_length=255, null=True, verbose_name='微信号')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('dept', models.CharField(max_length=255, null=True, verbose_name='部门')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='电话号码')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='电子邮件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否存活')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='User.role')),
            ],
            options={
                'db_table': 'dms_users',
            },
        ),
        migrations.CreateModel(
            name='PermissionAssignment',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='权限分配映射编号')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.permission')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.role')),
            ],
            options={
                'db_table': 'dms_permission_assignment',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='User.PermissionAssignment', to='User.Permission'),
        ),
    ]
