# Generated by Django 3.2.1 on 2021-05-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210506_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrow_count',
            field=models.IntegerField(default=5, verbose_name='可借阅次数'),
        ),
    ]
