# Generated by Django 3.2.1 on 2021-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_borrow_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True, verbose_name='头像地址'),
        ),
    ]
