# Generated by Django 3.2.1 on 2021-05-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_face_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='邮箱分配验证码记录的编号')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='电子邮件')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='电子邮件')),
                ('expire', models.DateTimeField(null=True, verbose_name='验证码失效时间')),
                ('apply_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_verification_codes', to='User.user')),
            ],
        ),
    ]
