# Generated by Django 3.2.1 on 2021-05-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_emailverificationcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverificationcode',
            table='dms_email_verification_code',
        ),
    ]
