# Generated by Django 3.2.1 on 2021-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_emailverificationcode_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='is_used',
            field=models.BooleanField(default=0, verbose_name='是否被用过'),
        ),
    ]
