# Generated by Django 3.2.1 on 2021-06-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210602_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='borrow_total_count',
            field=models.IntegerField(default=0, verbose_name='该角色可借阅总量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='borrow_count',
            field=models.IntegerField(default=0, verbose_name='可借阅次数'),
        ),
    ]
