# Generated by Django 3.2.1 on 2021-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210602_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(max_length=255, null=True, verbose_name='微信唯一编号'),
        ),
    ]
