# Generated by Django 3.2.1 on 2021-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_user_wechat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='角色编号'),
        ),
    ]
