from django.urls import path
from File.views import (index, getChildFolders, getFilesData, getFolderPosition, addNewFile, 
    getFileBasicInfo, previewFile, downloadFile, downloadFolder, deleteFile, deleteSelectionFiles, 
    getFileEditInfo, getChildPositions, addNewVersion, editFile, deleteFilingBox, addNewFiling, 
    getEditFilingInfo, editFiling, getFileApprovers, addNewBorrowRecord, getMyBorrowRecord, getMyBorrowRecords, 
    getManageBorrowRecord, getManageBorrowRecords, handleReturnFile, handleUrgeFile, handleDeleteBorrowRecord, 
    handleAgreeFile, handleRefuseFile, handleConfirmFile, agreeSelectionRecords, refuseSelectionRecords, 
    confirmSelectionRecords, deleteSelectionRecords, getFilingAudits, getFileAudits, exportFilingAudits, 
    exportFileAudits)


urlpatterns = [
    path("Index", index),
    path("ChildFolders", getChildFolders),
    path("FilesData", getFilesData),
    path("FolderPosition", getFolderPosition),
    path("NewFile", addNewFile),
    path("FileBasicInfo", getFileBasicInfo),
    path("PreviewFile", previewFile),
    path("DownloadFile", downloadFile),
    path("DownloadFolder", downloadFolder),
    path("DeleteFile", deleteFile),
    path("DeleteSelectionFiles", deleteSelectionFiles),
    path("FileEditInfo", getFileEditInfo),
    path("ChildPositions", getChildPositions),
    path("NewVersion", addNewVersion),
    path("EditFile", editFile),
    path("DeleteFilingBox", deleteFilingBox),
    path("NewFiling", addNewFiling),
    path("EditFilingInfo", getEditFilingInfo),
    path("EditFiling", editFiling),
    path("FileApprovers", getFileApprovers),
    path("NewBorrowRecord", addNewBorrowRecord),
    path("MyBorrowRecord", getMyBorrowRecord),
    path("MyBorrowRecords", getMyBorrowRecords),
    path("ManageBorrowRecord", getManageBorrowRecord),
    path("ManageBorrowRecords", getManageBorrowRecords),
    path("ReturnFile", handleReturnFile),
    path("UrgeFile", handleUrgeFile),
    path("DeleteBorrowRecord", handleDeleteBorrowRecord),
    path("AgreeFile", handleAgreeFile),
    path("RefuseFile", handleRefuseFile),
    path("ConfirmFile", handleConfirmFile),
    path("AgreeSelectionRecords", agreeSelectionRecords),
    path("RefuseSelectionRecords", refuseSelectionRecords),
    path("ConfirmSelectionRecords", confirmSelectionRecords),
    path("DeleteSelectionRecords", deleteSelectionRecords),
    path("FilingAudits", getFilingAudits),
    path("FileAudits", getFileAudits),
    path("ExportFilingAudits", exportFilingAudits),
    path("ExportFileAudits", exportFileAudits),
]