from django.urls import path
from User.views import (index, login, validate, getNewPermitUser, getUserBasicInfo, editUserBasicInfo, 
    getAvatar, updateAvatar, getUserSecurityInfo, modifyPassword, sendEmailVerificationCode, modifyEmail, 
    handleFaceVerify, handleFaceRecognitionLogin, getUsers, handleDeleteUser, handleDeleteSelectionUsers, 
    getUserInfo, handleRecoverUser, handleEditUser, getDepartmentsAndRolesList, addNewUser, handleImportNewUsers, 
    getRoles, handleModifyRolePermissions, handleModifyBorrowTotalCount, addNewRole)

urlpatterns = [
    path("Index", index),
    path("Login", login),
    path("Validate", validate),
    path("NewPermitUser", getNewPermitUser),
    path("UserBasicInfo", getUserBasicInfo),
    path("EditUserBasicInfo", editUserBasicInfo),
    path("Avatar", getAvatar),
    path("UpdateAvatar", updateAvatar),
    path("UserSecurityInfo", getUserSecurityInfo),
    path("ModifyPassword", modifyPassword),
    path("EmailVerificationCode", sendEmailVerificationCode),
    path("ModifyEmail", modifyEmail),
    path("FaceVerify", handleFaceVerify),
    path("FaceRecognitionLogin", handleFaceRecognitionLogin),
    path("Users", getUsers),
    path("DeleteUser", handleDeleteUser),
    path("DeleteSelectionUsers", handleDeleteSelectionUsers),
    path("UserInfo", getUserInfo),
    path("RecoverUser", handleRecoverUser),
    path("EditUser", handleEditUser),
    path("DepartmentsAndRolesList", getDepartmentsAndRolesList),
    path("NewUser", addNewUser),
    path("ImportNewUsers", handleImportNewUsers),
    path("Roles", getRoles),
    path("ModifyRolePermissions", handleModifyRolePermissions),
    path("ModifyBorrowTotalCount", handleModifyBorrowTotalCount),
    path("NewRole", addNewRole),
]